spring:
  security:
    oauth2:
      client:
        registration:
          keycloak-oidc:
            provider: keycloak
            client-name: Keycloak
            client-id: keycloak-experiments-app
            client-secret: jsVmxWrOHY73A354nvxwFyG7CKGNHJK0
            authorization-grant-type: authorization_code
            scope:
              - openid
              - email
              - profile
        provider:
          keycloak:
            issuer-uri: http://localhost:8083/realms/my-test-realm