spring:
  security:
    oauth2:
      client:
        registration:
          keycloak-oidc:
            provider: keycloak
            client-name: Keycloak
            client-id: keycloak-experiments-app
            client-secret: F6LjkcWOdwTsg3R6vV8V4bn5ePRI1YlY
            authorization-grant-type: authorization_code
            scope:
              - openid
              - email
              - profile

          github-oidc:
            provider: github
            client-name: GitHub
            client-id: ${GITHUB_OIDC_CLIENT_ID}
            client-secret: ${GITHUB_OIDC_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/github-oidc
            scope:
              - read:user
              - user:email

        provider:
          keycloak:
            issuer-uri: http://localhost:8083/realms/my-test-realm

          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
            user-name-attribute: login